// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Incubadora_v3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
lv_obj_t * ui_Screen;
lv_obj_t * ui_ProcessValue;
lv_obj_t * ui_pv;
lv_obj_t * ui_cc;
lv_obj_t * ui_iotlabel;
lv_obj_t * ui_lastSP;
lv_obj_t * ui_lastSPlabel;
lv_obj_t * ui_cc1;
lv_obj_t * ui_pvlabel;
lv_obj_t * ui_sensorDetection1;
lv_obj_t * ui_splabel;
void ui_event_increaseSP(lv_event_t * e);
lv_obj_t * ui_increaseSP;
lv_obj_t * ui_Label1;
void ui_event_decreaseSP(lv_event_t * e);
lv_obj_t * ui_decreaseSP;
lv_obj_t * ui_Label2;
lv_obj_t * ui_alarmsPanel;
lv_obj_t * ui_tempUpperLimit;
lv_obj_t * ui_tempLowerLimit;
lv_obj_t * ui_sensorDetection;
lv_obj_t * ui_resistorDetection;
lv_obj_t * ui_emergencyStop;
lv_obj_t * ui_tempUpperLimitLabel;
lv_obj_t * ui_tempLowerLimitLabel;
lv_obj_t * ui_sensorDetectionLabel;
lv_obj_t * ui_resistorDetectionLabel;
lv_obj_t * ui_emergencyStopLabel;
lv_obj_t * ui_indicadoresAlarmaLabel;
lv_obj_t * ui_titulo;
lv_obj_t * ui_powerLabel;
lv_obj_t * ui_PanelPowerBar;
lv_obj_t * ui_powerBar;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_increaseSP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        increaseSP(e);
    }
}
void ui_event_decreaseSP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        decreaseTemp(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen);
}
