// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Incubadora_v3

#ifndef _INCUBADORA_V3_UI_H
#define _INCUBADORA_V3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
extern lv_obj_t * ui_Screen;
extern lv_obj_t * ui_ProcessValue;
extern lv_obj_t * ui_pv;
extern lv_obj_t * ui_cc;
extern lv_obj_t * ui_iotlabel;
extern lv_obj_t * ui_lastSP;
extern lv_obj_t * ui_lastSPlabel;
extern lv_obj_t * ui_cc1;
extern lv_obj_t * ui_pvlabel;
extern lv_obj_t * ui_sensorDetection1;
extern lv_obj_t * ui_splabel;
void ui_event_increaseSP(lv_event_t * e);
extern lv_obj_t * ui_increaseSP;
extern lv_obj_t * ui_Label1;
void ui_event_decreaseSP(lv_event_t * e);
extern lv_obj_t * ui_decreaseSP;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_alarmsPanel;
extern lv_obj_t * ui_tempUpperLimit;
extern lv_obj_t * ui_tempLowerLimit;
extern lv_obj_t * ui_sensorDetection;
extern lv_obj_t * ui_resistorDetection;
extern lv_obj_t * ui_emergencyStop;
extern lv_obj_t * ui_tempUpperLimitLabel;
extern lv_obj_t * ui_tempLowerLimitLabel;
extern lv_obj_t * ui_sensorDetectionLabel;
extern lv_obj_t * ui_resistorDetectionLabel;
extern lv_obj_t * ui_emergencyStopLabel;
extern lv_obj_t * ui_indicadoresAlarmaLabel;
extern lv_obj_t * ui_titulo;
extern lv_obj_t * ui_powerLabel;
extern lv_obj_t * ui_PanelPowerBar;
extern lv_obj_t * ui_powerBar;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
