// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Incubadora

#include "ui.h"
#include <stdlib.h>
#include "globals.h"

const char* upperLimitStr = "38.0";
const char* lowerLimitStr = "36.0";
float upperLimit = 38.0;
float lowerLimit = 36.0;
float currentSP = 36.0;

float finalValue = 0.0;
bool flagIoT = false;


void insertSetPoint(lv_event_t * e)
{
	/*const char* text = lv_textarea_get_text(ui_SetPoint);
  float value = atof(text);
  if (value >= upperLimit){
    finalValue = upperLimit;
    lv_textarea_set_text(ui_SetPoint, upperLimitStr);
  }else if (value <= lowerLimit){
    finalValue = lowerLimit;
    lv_textarea_set_text(ui_SetPoint, lowerLimitStr);
  }
  else{
    finalValue = value;
  }
  
  flagSendData = true;
  char buffer[5]; 
  dtostrf(finalValue, 4, 1, buffer);
  const char* finalValueStr = buffer;

  if (flagModeSelector){
    lv_label_set_text(ui_mv, finalValueStr);
  }else{
    lv_label_set_text(ui_lastSPlabel, finalValueStr);
  }*/
}

void iotChecked(lv_event_t * e)
{
	flagIoT = true;
}

void iotUnchecked(lv_event_t * e)
{
	flagIoT = false;
}


void increaseSP(lv_event_t * e)
{
	if (currentSP < upperLimit){
    currentSP = currentSP + 0.1;
  }
  else{
    currentSP = upperLimit;
  }
  
  finalValue = currentSP;
  char buffer[5]; 
  dtostrf(finalValue, 4, 1, buffer);
  const char* finalValueStr = buffer;
  lv_label_set_text(ui_lastSPlabel, finalValueStr);
  flagSendData = true;
}

void decreaseTemp(lv_event_t * e)
{
	if (currentSP > lowerLimit){
    currentSP = currentSP - 0.1;
  }
  else{
    currentSP = lowerLimit;
  }
  
  finalValue = currentSP;
  char buffer[5];
  dtostrf(finalValue, 4, 1, buffer);
  const char* finalValueStr = buffer;
  lv_label_set_text(ui_lastSPlabel, finalValueStr);
  flagSendData = true;
}
