// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Incubadora_v3

#include "ui.h"

void ui_Screen_screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProcessValue = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_ProcessValue, 150);
    lv_obj_set_height(ui_ProcessValue, 80);
    lv_obj_set_x(ui_ProcessValue, -220);
    lv_obj_set_y(ui_ProcessValue, -90);
    lv_obj_set_align(ui_ProcessValue, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProcessValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pv = lv_label_create(ui_ProcessValue);
    lv_obj_set_width(ui_pv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pv, -30);
    lv_obj_set_y(ui_pv, 0);
    lv_obj_set_align(ui_pv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pv, "--.-");
    lv_obj_set_style_text_font(ui_pv, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cc = lv_label_create(ui_ProcessValue);
    lv_obj_set_width(ui_cc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cc, 40);
    lv_obj_set_y(ui_cc, 0);
    lv_obj_set_align(ui_cc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cc, "°C");
    lv_obj_set_style_text_font(ui_cc, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iotlabel = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_iotlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iotlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iotlabel, 230);
    lv_obj_set_y(ui_iotlabel, -90);
    lv_obj_set_align(ui_iotlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_iotlabel, "Control Remoto");

    ui_lastSP = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_lastSP, 150);
    lv_obj_set_height(ui_lastSP, 80);
    lv_obj_set_x(ui_lastSP, -220);
    lv_obj_set_y(ui_lastSP, 110);
    lv_obj_set_align(ui_lastSP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lastSP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastSPlabel = lv_label_create(ui_lastSP);
    lv_obj_set_width(ui_lastSPlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastSPlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastSPlabel, -25);
    lv_obj_set_y(ui_lastSPlabel, 0);
    lv_obj_set_align(ui_lastSPlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastSPlabel, "36.0");
    lv_obj_set_style_text_font(ui_lastSPlabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cc1 = lv_label_create(ui_lastSP);
    lv_obj_set_width(ui_cc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cc1, 40);
    lv_obj_set_y(ui_cc1, 1);
    lv_obj_set_align(ui_cc1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cc1, "°C");
    lv_obj_set_style_text_font(ui_cc1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pvlabel = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_pvlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pvlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pvlabel, -220);
    lv_obj_set_y(ui_pvlabel, -20);
    lv_obj_set_align(ui_pvlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pvlabel, "Sensor de Piel");
    lv_obj_set_style_text_font(ui_pvlabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorDetection1 = lv_btn_create(ui_Screen);
    lv_obj_set_width(ui_sensorDetection1, 30);
    lv_obj_set_height(ui_sensorDetection1, 30);
    lv_obj_set_x(ui_sensorDetection1, 310);
    lv_obj_set_y(ui_sensorDetection1, -90);
    lv_obj_set_align(ui_sensorDetection1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sensorDetection1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensorDetection1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sensorDetection1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorDetection1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sensorDetection1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sensorDetection1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorDetection1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splabel = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_splabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_splabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_splabel, -220);
    lv_obj_set_y(ui_splabel, 180);
    lv_obj_set_align(ui_splabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_splabel, "Configuracion de Temperatura");
    lv_obj_set_style_text_font(ui_splabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_increaseSP = lv_btn_create(ui_Screen);
    lv_obj_set_width(ui_increaseSP, 52);
    lv_obj_set_height(ui_increaseSP, 50);
    lv_obj_set_x(ui_increaseSP, -90);
    lv_obj_set_y(ui_increaseSP, 110);
    lv_obj_set_align(ui_increaseSP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_increaseSP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_increaseSP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_increaseSP, lv_color_hex(0x0B8531), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_increaseSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_increaseSP);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "+");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_decreaseSP = lv_btn_create(ui_Screen);
    lv_obj_set_width(ui_decreaseSP, 52);
    lv_obj_set_height(ui_decreaseSP, 50);
    lv_obj_set_x(ui_decreaseSP, -350);
    lv_obj_set_y(ui_decreaseSP, 110);
    lv_obj_set_align(ui_decreaseSP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_decreaseSP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_decreaseSP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_decreaseSP, lv_color_hex(0xC6050F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_decreaseSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_decreaseSP);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmsPanel = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_alarmsPanel, 251);
    lv_obj_set_height(ui_alarmsPanel, 231);
    lv_obj_set_x(ui_alarmsPanel, 240);
    lv_obj_set_y(ui_alarmsPanel, 100);
    lv_obj_set_align(ui_alarmsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_alarmsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempUpperLimit = lv_btn_create(ui_alarmsPanel);
    lv_obj_set_width(ui_tempUpperLimit, 30);
    lv_obj_set_height(ui_tempUpperLimit, 30);
    lv_obj_set_x(ui_tempUpperLimit, -90);
    lv_obj_set_y(ui_tempUpperLimit, -80);
    lv_obj_set_align(ui_tempUpperLimit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempUpperLimit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tempUpperLimit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempUpperLimit, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempUpperLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempUpperLimit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempUpperLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempUpperLimit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLowerLimit = lv_btn_create(ui_alarmsPanel);
    lv_obj_set_width(ui_tempLowerLimit, 30);
    lv_obj_set_height(ui_tempLowerLimit, 30);
    lv_obj_set_x(ui_tempLowerLimit, -90);
    lv_obj_set_y(ui_tempLowerLimit, -40);
    lv_obj_set_align(ui_tempLowerLimit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempLowerLimit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tempLowerLimit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempLowerLimit, lv_color_hex(0x0800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempLowerLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempLowerLimit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempLowerLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempLowerLimit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorDetection = lv_btn_create(ui_alarmsPanel);
    lv_obj_set_width(ui_sensorDetection, 30);
    lv_obj_set_height(ui_sensorDetection, 30);
    lv_obj_set_x(ui_sensorDetection, -90);
    lv_obj_set_y(ui_sensorDetection, 0);
    lv_obj_set_align(ui_sensorDetection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sensorDetection, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sensorDetection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sensorDetection, lv_color_hex(0x00FF0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorDetection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sensorDetection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sensorDetection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sensorDetection, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resistorDetection = lv_btn_create(ui_alarmsPanel);
    lv_obj_set_width(ui_resistorDetection, 30);
    lv_obj_set_height(ui_resistorDetection, 30);
    lv_obj_set_x(ui_resistorDetection, -90);
    lv_obj_set_y(ui_resistorDetection, 40);
    lv_obj_set_align(ui_resistorDetection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_resistorDetection, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_resistorDetection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resistorDetection, lv_color_hex(0xD4FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resistorDetection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_resistorDetection, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_emergencyStop = lv_btn_create(ui_alarmsPanel);
    lv_obj_set_width(ui_emergencyStop, 30);
    lv_obj_set_height(ui_emergencyStop, 30);
    lv_obj_set_x(ui_emergencyStop, -90);
    lv_obj_set_y(ui_emergencyStop, 80);
    lv_obj_set_align(ui_emergencyStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_emergencyStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_emergencyStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_emergencyStop, lv_color_hex(0xFF7D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_emergencyStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_emergencyStop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempUpperLimitLabel = lv_label_create(ui_alarmsPanel);
    lv_obj_set_width(ui_tempUpperLimitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempUpperLimitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempUpperLimitLabel, 30);
    lv_obj_set_y(ui_tempUpperLimitLabel, -80);
    lv_obj_set_align(ui_tempUpperLimitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempUpperLimitLabel, "Temperatura alta");

    ui_tempLowerLimitLabel = lv_label_create(ui_alarmsPanel);
    lv_obj_set_width(ui_tempLowerLimitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLowerLimitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLowerLimitLabel, 30);
    lv_obj_set_y(ui_tempLowerLimitLabel, -40);
    lv_obj_set_align(ui_tempLowerLimitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLowerLimitLabel, "Temperatura baja");

    ui_sensorDetectionLabel = lv_label_create(ui_alarmsPanel);
    lv_obj_set_width(ui_sensorDetectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorDetectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorDetectionLabel, 30);
    lv_obj_set_y(ui_sensorDetectionLabel, 0);
    lv_obj_set_align(ui_sensorDetectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorDetectionLabel, "Sensor");

    ui_resistorDetectionLabel = lv_label_create(ui_alarmsPanel);
    lv_obj_set_width(ui_resistorDetectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_resistorDetectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_resistorDetectionLabel, 30);
    lv_obj_set_y(ui_resistorDetectionLabel, 40);
    lv_obj_set_align(ui_resistorDetectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resistorDetectionLabel, "Calefactor");

    ui_emergencyStopLabel = lv_label_create(ui_alarmsPanel);
    lv_obj_set_width(ui_emergencyStopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_emergencyStopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_emergencyStopLabel, 30);
    lv_obj_set_y(ui_emergencyStopLabel, 80);
    lv_obj_set_align(ui_emergencyStopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_emergencyStopLabel, "Parada de emergencia");

    ui_indicadoresAlarmaLabel = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_indicadoresAlarmaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indicadoresAlarmaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indicadoresAlarmaLabel, 240);
    lv_obj_set_y(ui_indicadoresAlarmaLabel, -45);
    lv_obj_set_align(ui_indicadoresAlarmaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_indicadoresAlarmaLabel, "Alarmas");
    lv_obj_set_style_text_font(ui_indicadoresAlarmaLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titulo = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_titulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titulo, 0);
    lv_obj_set_y(ui_titulo, -190);
    lv_obj_set_align(ui_titulo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titulo, "PHOENIX NOC 100\nFOSCAL INTERNACIONAL");
    lv_obj_set_style_text_align(ui_titulo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_titulo, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerLabel = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_powerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerLabel, 0);
    lv_obj_set_y(ui_powerLabel, -50);
    lv_obj_set_align(ui_powerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel, "Porcentaje de Potencia");
    lv_obj_set_style_text_font(ui_powerLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPowerBar = lv_obj_create(ui_Screen);
    lv_obj_set_width(ui_PanelPowerBar, 200);
    lv_obj_set_height(ui_PanelPowerBar, 55);
    lv_obj_set_x(ui_PanelPowerBar, 0);
    lv_obj_set_y(ui_PanelPowerBar, -90);
    lv_obj_set_align(ui_PanelPowerBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPowerBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powerBar = lv_bar_create(ui_PanelPowerBar);
    lv_bar_set_value(ui_powerBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_powerBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerBar, 180);
    lv_obj_set_height(ui_powerBar, 10);
    lv_obj_set_x(ui_powerBar, 0);
    lv_obj_set_y(ui_powerBar, 10);
    lv_obj_set_align(ui_powerBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_powerBar, lv_color_hex(0x68BDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_powerBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_PanelPowerBar);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -80);
    lv_obj_set_y(ui_Label3, -10);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "0%");

    ui_Label4 = lv_label_create(ui_PanelPowerBar);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 80);
    lv_obj_set_y(ui_Label4, -10);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "100%");

    ui_Label5 = lv_label_create(ui_PanelPowerBar);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -10);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "50%");

    lv_obj_add_event_cb(ui_increaseSP, ui_event_increaseSP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_decreaseSP, ui_event_decreaseSP, LV_EVENT_ALL, NULL);

}
