// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Incubadora_v3

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void iotChecked(lv_event_t * e);
void iotUnchecked(lv_event_t * e);
void increaseSP(lv_event_t * e);
void decreaseTemp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
